### ISSUE TITLE
Conditon provision in NAMM item document

### ISSUE THREAD

**Issue by MUSICKIX** [namm-standards/standards#2]
Does the NAMM item document have a provision for product condition and I just missed it? If it does, are there specific condition keywords that should be used?

**Comment by McGloine** [comment]
The schema, [Item-v2015.1.xsd] does have a node for condition however it is not restricted to specific values. As I recall discussions from years ago, many people felt that would limit the use for those with a complex grading system. Like many other nodes many people wanted it left up to trading partners to agree to valid values between them. New, Used and Refurbished would not be enough in several examples given.

`<xs:element name="Condition" minOccurs="0" type="xs:string" />`

**Comment by MUSICKIX** [comment]
Thanks Bill. 
On another note, did you receive the file of internet Korg products which I sent to you? 
Myles 
----- Original Message -----
